version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Expose the port Webpack dev server runs on
    # volumes:
    #   - .:/usr/src/app # Mount the current directory to the container's working directory
    #   - /usr/src/app/node_modules # Avoid overriding node_modules in the container
    environment:
      REACT_APP_CLERK_PUBLISHABLE_KEY: pk_test_c291Z2h0LXdvcm0tOC5jbGVyay5hY2NvdW50cy5kZXYk
      REACT_APP_LOGO_URL: https://marketplace.canva.com/EAGUe-CYFgU/1/0/1600w/canva-grey-orange-modern-circle-class-logo-Aro9ea9TDP4.jpg
      REACT_APP_BRAND_NAME: "Rimberio School"
      REACT_APP_PROJECTS_LABEL: "Projects"
      REACT_APP_EDIT_PROJECTS_LABEL: "Project"
      REACT_APP_PROJECTS_ROUTE: "project"
      REACT_APP_ENABLE_PROJECTS: true
      REACT_APP_KNOWLEDGE_BASE_LABEL: "KBs"
      REACT_APP_EDIT_KNOWLEDGE_BASE_LABEL: "Knowledge Base"
      REACT_APP_KNOWLEDGE_BASE_ROUTE: "knowledge"
      REACT_APP_ENABLE_KNOWLEDGE_BASES: true
      REACT_APP_ENABLE_CHATS: true
      REACT_APP_CHAT_ROUTE: c
      REACT_APP_ENABLE_HISTORY: true
      REACT_APP_GOOGLE_ANALYTICS_ENABLE: true
      REACT_APP_GOOGLE_ANALYTICS_CODE: G-W9LZEK9WJR
